import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Form from '@/components/UI/Form';
import { useAddress } from '@thirdweb-dev/react';

export default function Home() {
  const address = useAddress();
  const { push } = useRouter();

  useEffect(() => {
    if (!address) {
      return;
    } else {
      push('/user/' + address);
    }
  }, [address]);
  return (
    <>
      <Head>
        <title>Bank Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Form />
      </main>
    </>
  );
}
